name: ConduitPlayerPoints
version: "${version}"
description: PlayerPoints economy bridge for Conduit
authors: [Alazso]
api-version: "26.1"
folia-supported: true
main: so.alaz.conduit.bridge.playerpoints.PlayerPointsBridgePlugin
dependencies:
  server:
    Conduit:
      load: BEFORE
      required: true
    PlayerPoints:
      load: BEFORE
      required: true
